
package com.soa.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CategoryService", targetNamespace = "http://soap.soa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoryService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveForest", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveForest")
    @ResponseWrapper(localName = "saveForestResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveForestResponse")
    public void saveForest(
        @WebParam(name = "arg0", targetNamespace = "")
        Forest arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveTower", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveTower")
    @ResponseWrapper(localName = "saveTowerResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveTowerResponse")
    public void saveTower(
        @WebParam(name = "arg0", targetNamespace = "")
        Tower arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveCave", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveCave")
    @ResponseWrapper(localName = "saveCaveResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveCaveResponse")
    public void saveCave(
        @WebParam(name = "arg0", targetNamespace = "")
        Cave arg0);

}
