
package com.soa.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HeroService", targetNamespace = "http://soap.soa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HeroService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveElf", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveElf")
    @ResponseWrapper(localName = "saveElfResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveElfResponse")
    public void saveElf(
        @WebParam(name = "arg0", targetNamespace = "")
        WsElfRequest arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyMana", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyMana")
    @ResponseWrapper(localName = "modifyManaResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyManaResponse")
    public void modifyMana(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveMag", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveMag")
    @ResponseWrapper(localName = "saveMagResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveMagResponse")
    public void saveMag(
        @WebParam(name = "arg0", targetNamespace = "")
        WsMagRequest arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyGold", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyGold")
    @ResponseWrapper(localName = "modifyGoldResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyGoldResponse")
    public void modifyGold(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modifyArrows", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyArrows")
    @ResponseWrapper(localName = "modifyArrowsResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.ModifyArrowsResponse")
    public void modifyArrows(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveDragon", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveDragon")
    @ResponseWrapper(localName = "saveDragonResponse", targetNamespace = "http://soap.soa.com/", className = "com.soa.soap.SaveDragonResponse")
    public void saveDragon(
        @WebParam(name = "arg0", targetNamespace = "")
        WsDragonRequest arg0);

}
