
package com.soa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Analyzer", targetNamespace = "http://ws.soa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Analyzer {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.soa.ws.Info
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "analyze", targetNamespace = "http://ws.soa.com/", className = "com.soa.ws.Analyze")
    @ResponseWrapper(localName = "analyzeResponse", targetNamespace = "http://ws.soa.com/", className = "com.soa.ws.AnalyzeResponse")
    @Action(input = "http://ws.soa.com/Analyzer/analyzeRequest", output = "http://ws.soa.com/Analyzer/analyzeResponse")
    public Info analyze(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
