
package com.soa.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnalyzerImplService", targetNamespace = "http://ws.soa.com/", wsdlLocation = "file:/C:/Users/plague/programming-projects/java/java-ee/Idea/soa/lab9/analyzer/analyzer.wsdl")
public class AnalyzerImplService
    extends Service
{

    private final static URL ANALYZERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANALYZERIMPLSERVICE_EXCEPTION;
    private final static QName ANALYZERIMPLSERVICE_QNAME = new QName("http://ws.soa.com/", "AnalyzerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/analzyer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANALYZERIMPLSERVICE_WSDL_LOCATION = url;
        ANALYZERIMPLSERVICE_EXCEPTION = e;
    }

    public AnalyzerImplService() {
        super(__getWsdlLocation(), ANALYZERIMPLSERVICE_QNAME);
    }

    public AnalyzerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANALYZERIMPLSERVICE_QNAME, features);
    }

    public AnalyzerImplService(URL wsdlLocation) {
        super(wsdlLocation, ANALYZERIMPLSERVICE_QNAME);
    }

    public AnalyzerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANALYZERIMPLSERVICE_QNAME, features);
    }

    public AnalyzerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalyzerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Analyzer
     */
    @WebEndpoint(name = "AnalyzerImplPort")
    public Analyzer getAnalyzerImplPort() {
        return super.getPort(new QName("http://ws.soa.com/", "AnalyzerImplPort"), Analyzer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Analyzer
     */
    @WebEndpoint(name = "AnalyzerImplPort")
    public Analyzer getAnalyzerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.com/", "AnalyzerImplPort"), Analyzer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANALYZERIMPLSERVICE_EXCEPTION!= null) {
            throw ANALYZERIMPLSERVICE_EXCEPTION;
        }
        return ANALYZERIMPLSERVICE_WSDL_LOCATION;
    }

}
