
package com.soa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VacationImplService", targetNamespace = "http://ws.soa.com/", wsdlLocation = "http://localhost:8080/vacation?wsdl")
public class VacationImplService
    extends Service
{

    private final static URL VACATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VACATIONIMPLSERVICE_EXCEPTION;
    private final static QName VACATIONIMPLSERVICE_QNAME = new QName("http://ws.soa.com/", "VacationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/vacation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VACATIONIMPLSERVICE_WSDL_LOCATION = url;
        VACATIONIMPLSERVICE_EXCEPTION = e;
    }

    public VacationImplService() {
        super(__getWsdlLocation(), VACATIONIMPLSERVICE_QNAME);
    }

    public VacationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VACATIONIMPLSERVICE_QNAME, features);
    }

    public VacationImplService(URL wsdlLocation) {
        super(wsdlLocation, VACATIONIMPLSERVICE_QNAME);
    }

    public VacationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VACATIONIMPLSERVICE_QNAME, features);
    }

    public VacationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VacationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Vacation
     */
    @WebEndpoint(name = "VacationImplPort")
    public Vacation getVacationImplPort() {
        return super.getPort(new QName("http://ws.soa.com/", "VacationImplPort"), Vacation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Vacation
     */
    @WebEndpoint(name = "VacationImplPort")
    public Vacation getVacationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.com/", "VacationImplPort"), Vacation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VACATIONIMPLSERVICE_EXCEPTION!= null) {
            throw VACATIONIMPLSERVICE_EXCEPTION;
        }
        return VACATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
