
package com.soa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Currency", targetNamespace = "http://ws.soa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Currency {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrencyByCode", targetNamespace = "http://ws.soa.com/", className = "com.soa.ws.GetCurrencyByCode")
    @ResponseWrapper(localName = "getCurrencyByCodeResponse", targetNamespace = "http://ws.soa.com/", className = "com.soa.ws.GetCurrencyByCodeResponse")
    @Action(input = "http://ws.soa.com/Currency/getCurrencyByCodeRequest", output = "http://ws.soa.com/Currency/getCurrencyByCodeResponse")
    public Double getCurrencyByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
