
package com.soa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrencyImplService", targetNamespace = "http://ws.soa.com/", wsdlLocation = "http://localhost:8080/currency?wsdl")
public class CurrencyImplService
    extends Service
{

    private final static URL CURRENCYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENCYIMPLSERVICE_EXCEPTION;
    private final static QName CURRENCYIMPLSERVICE_QNAME = new QName("http://ws.soa.com/", "CurrencyImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/currency?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENCYIMPLSERVICE_WSDL_LOCATION = url;
        CURRENCYIMPLSERVICE_EXCEPTION = e;
    }

    public CurrencyImplService() {
        super(__getWsdlLocation(), CURRENCYIMPLSERVICE_QNAME);
    }

    public CurrencyImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENCYIMPLSERVICE_QNAME, features);
    }

    public CurrencyImplService(URL wsdlLocation) {
        super(wsdlLocation, CURRENCYIMPLSERVICE_QNAME);
    }

    public CurrencyImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENCYIMPLSERVICE_QNAME, features);
    }

    public CurrencyImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Currency
     */
    @WebEndpoint(name = "CurrencyImplPort")
    public Currency getCurrencyImplPort() {
        return super.getPort(new QName("http://ws.soa.com/", "CurrencyImplPort"), Currency.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Currency
     */
    @WebEndpoint(name = "CurrencyImplPort")
    public Currency getCurrencyImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soa.com/", "CurrencyImplPort"), Currency.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENCYIMPLSERVICE_EXCEPTION!= null) {
            throw CURRENCYIMPLSERVICE_EXCEPTION;
        }
        return CURRENCYIMPLSERVICE_WSDL_LOCATION;
    }

}
